# This action is just a test
name: Snyk

on: push

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-test
      SKIP_NODE: true
      NODE_PACKAGE_JSON_FILES_MISSING_LOCK: package.json aggreagate-polls/package.json
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
